#!/bin/bash
# arch-tag: Debhelper script for Haskell
#
# Copyright (C) 2009 Marco Túlio Gontijo e Silva <marcot@debian.org>
# Copyright (C) 2014 Joachim Breitner <nomeata@debian.org>
#
# Based on mk-haskell-depends by Martin Sjögren <sjogren@debian.org>
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

. /usr/share/haskell-devscripts/Dh_Haskell.sh

# PS4=" + dh_haskell_shlibdeps> "
# set -x

pkgs=`dh_listpackages $args`

for pkg in $pkgs
do
    ext=`package_ext ${pkg}`
    case "$ext" in
        dev)
            if [ -z "$files" ] ; then
                files=`find_config_for_ghc $pkg`
            fi
            ;;
    esac
done

if [ -z "$files" ]
then
        echo "dh_haskell_shlibdeps - no installed package description files found" >&2
        exit 1
fi

T_DIR=debian/dh_haskell_shlibdeps
mkdir $T_DIR 2> /dev/null || true

args=""
cpkgs="`basename -s .conf $files`"
ghcpkg="`tmp_package_db $files`"
for cpkg in ${cpkgs}
do
    ldirs="`${ghcpkg} --simple-output field "${cpkg}" library-dirs`"
    for dir in ${ldirs}
    do
        args="$args -L$dir"
    done
    elibs="`${ghcpkg} --simple-output field "${cpkg}" extra-libraries`"
    for lib in ${elibs}
    do
        args="$args -l$lib"
    done
done

echo 'int main (void) {}' > $T_DIR/probe.c
gcc $args $T_DIR/probe.c -o $T_DIR/probe

for pkg in $pkgs
do
    ext=`package_ext ${pkg}`
    case "$ext" in
        dev)
            dpkg-shlibdeps --warnings=1 -Tdebian/$pkg.substvars $T_DIR/probe
            ;;
    esac
done
