#!/bin/sh

# Copyright © 2022 Felix Lechner <felix.lechner@lease-up.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# this script exists only for two calls from
#
# - https://sources.debian.org/src/gitit/0.13.0.0+dfsg-2/debian/rules/?hl=22#L22
# - https://sources.debian.org/src/haskell-shake/0.19.1-2/debian/rules/?hl=24#L24

export DEB_DEFAULT_COMPILER=ghc
export DEB_GHC_DATABASE=debian/tmp-db
export DEB_SETUP_BIN_NAME=debian/hlibrary.setup

dh_haskell_extra_depends_ghc
